--------------------------------------------------------
--  Fichier créé - lundi-avril-26-2021   
--------------------------------------------------------
DROP TABLE "HANEN"."CAMERAS";
DROP TABLE "HANEN"."ECRAN";
DROP TABLE "HANEN"."ELECTRO";
DROP TABLE "HANEN"."ENFANTS";
DROP TABLE "HANEN"."LAMPES";
DROP TABLE "HANEN"."NUTRITION";
DROP TABLE "HANEN"."PARENTS";
DROP TABLE "HANEN"."PORTE";
DROP TABLE "HANEN"."SITE";
DROP TABLE "HANEN"."TEMPS";
--------------------------------------------------------
--  DDL for Table CAMERAS
--------------------------------------------------------

  CREATE TABLE "HANEN"."CAMERAS" 
   (	"NUM_CAMERAS" NUMBER, 
	"LIEU_CAMERAS" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ECRAN
--------------------------------------------------------

  CREATE TABLE "HANEN"."ECRAN" 
   (	"ID" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ELECTRO
--------------------------------------------------------

  CREATE TABLE "HANEN"."ELECTRO" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"ETAT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENFANTS
--------------------------------------------------------

  CREATE TABLE "HANEN"."ENFANTS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM_ENF" VARCHAR2(20 BYTE), 
	"PRENOM_ENF" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LAMPES
--------------------------------------------------------

  CREATE TABLE "HANEN"."LAMPES" 
   (	"NUM_LAMPES" NUMBER, 
	"CHAMBRE" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NUTRITION
--------------------------------------------------------

  CREATE TABLE "HANEN"."NUTRITION" 
   (	"DEJEUNER" VARCHAR2(20 BYTE), 
	"DINER" VARCHAR2(20 BYTE), 
	"PTT_DEJ" VARCHAR2(20 BYTE), 
	"CALORIES" NUMBER(*,0), 
	"DATER" VARCHAR2(20 BYTE), 
	"EMPREINTE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARENTS
--------------------------------------------------------

  CREATE TABLE "HANEN"."PARENTS" 
   (	"NOM_DE_FAMILLE" VARCHAR2(20 BYTE), 
	"PRENOM_RES" VARCHAR2(20 BYTE), 
	"CIN" NUMBER, 
	"EMAIL_RESP" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"PAYS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PORTE
--------------------------------------------------------

  CREATE TABLE "HANEN"."PORTE" 
   (	"NUM_PORTE" NUMBER, 
	"CODE" NUMBER, 
	"TOUVERTURE" VARCHAR2(20 BYTE), 
	"TFERMETURE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SITE
--------------------------------------------------------

  CREATE TABLE "HANEN"."SITE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"ADRESS" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEMPS
--------------------------------------------------------

  CREATE TABLE "HANEN"."TEMPS" 
   (	"EMPLOI" VARCHAR2(20 BYTE), 
	"RENDEZ_VOUS" VARCHAR2(20 BYTE), 
	"DATEH" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HANEN.CAMERAS
SET DEFINE OFF;
REM INSERTING into HANEN.ECRAN
SET DEFINE OFF;
REM INSERTING into HANEN.ELECTRO
SET DEFINE OFF;
REM INSERTING into HANEN.ENFANTS
SET DEFINE OFF;
REM INSERTING into HANEN.LAMPES
SET DEFINE OFF;
REM INSERTING into HANEN.NUTRITION
SET DEFINE OFF;
REM INSERTING into HANEN.PARENTS
SET DEFINE OFF;
REM INSERTING into HANEN.PORTE
SET DEFINE OFF;
REM INSERTING into HANEN.SITE
SET DEFINE OFF;
REM INSERTING into HANEN.TEMPS
SET DEFINE OFF;
Insert into HANEN.TEMPS (EMPLOI,RENDEZ_VOUS,DATEH) values ('ddd','rrrr','zzz');
Insert into HANEN.TEMPS (EMPLOI,RENDEZ_VOUS,DATEH) values ('kakaka','12/12/2000','pas encore');
--------------------------------------------------------
--  DDL for Index CAMERA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HANEN"."CAMERA_PK" ON "HANEN"."CAMERAS" ("NUM_CAMERAS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ECRAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HANEN"."ECRAN_PK" ON "HANEN"."ECRAN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ELECTRO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HANEN"."ELECTRO_PK" ON "HANEN"."ELECTRO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ENFANTS_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "HANEN"."ENFANTS_PK1" ON "HANEN"."ENFANTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LAMPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HANEN"."LAMPES_PK" ON "HANEN"."LAMPES" ("NUM_LAMPES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NUTRITION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HANEN"."NUTRITION_PK" ON "HANEN"."NUTRITION" ("DATER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index INSCRIPTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HANEN"."INSCRIPTION_PK" ON "HANEN"."PARENTS" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PORTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HANEN"."PORTE_PK" ON "HANEN"."PORTE" ("NUM_PORTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SITE_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "HANEN"."SITE_PK1" ON "HANEN"."SITE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TEMPS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HANEN"."TEMPS_PK" ON "HANEN"."TEMPS" ("DATEH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CAMERAS
--------------------------------------------------------

  ALTER TABLE "HANEN"."CAMERAS" ADD CONSTRAINT "CAMERA_PK" PRIMARY KEY ("NUM_CAMERAS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HANEN"."CAMERAS" MODIFY ("NUM_CAMERAS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ECRAN
--------------------------------------------------------

  ALTER TABLE "HANEN"."ECRAN" ADD CONSTRAINT "ECRAN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HANEN"."ECRAN" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ELECTRO
--------------------------------------------------------

  ALTER TABLE "HANEN"."ELECTRO" ADD CONSTRAINT "ELECTRO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HANEN"."ELECTRO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENFANTS
--------------------------------------------------------

  ALTER TABLE "HANEN"."ENFANTS" ADD CONSTRAINT "ENFANTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HANEN"."ENFANTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LAMPES
--------------------------------------------------------

  ALTER TABLE "HANEN"."LAMPES" ADD CONSTRAINT "LAMPES_PK" PRIMARY KEY ("NUM_LAMPES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HANEN"."LAMPES" MODIFY ("NUM_LAMPES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NUTRITION
--------------------------------------------------------

  ALTER TABLE "HANEN"."NUTRITION" ADD CONSTRAINT "NUTRITION_PK" PRIMARY KEY ("DATER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HANEN"."NUTRITION" MODIFY ("DATER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARENTS
--------------------------------------------------------

  ALTER TABLE "HANEN"."PARENTS" ADD CONSTRAINT "INSCRIPTION_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HANEN"."PARENTS" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PORTE
--------------------------------------------------------

  ALTER TABLE "HANEN"."PORTE" ADD CONSTRAINT "PORTE_PK" PRIMARY KEY ("NUM_PORTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HANEN"."PORTE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "HANEN"."PORTE" MODIFY ("NUM_PORTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SITE
--------------------------------------------------------

  ALTER TABLE "HANEN"."SITE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "HANEN"."SITE" MODIFY ("ADRESS" NOT NULL ENABLE);
  ALTER TABLE "HANEN"."SITE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "HANEN"."SITE" ADD CONSTRAINT "SITE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEMPS
--------------------------------------------------------

  ALTER TABLE "HANEN"."TEMPS" ADD CONSTRAINT "TEMPS_PK" PRIMARY KEY ("DATEH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HANEN"."TEMPS" MODIFY ("DATEH" NOT NULL ENABLE);
  ALTER TABLE "HANEN"."TEMPS" MODIFY ("RENDEZ_VOUS" NOT NULL ENABLE);
